doctrine:
    dbal:
        types:
            ulid_id: AwdEs\EsLibBundle\Doctrine\DBAL\Types\UlidIdType
            jsonb_or_json: AwdEs\EsLibBundle\Doctrine\DBAL\Types\JsonbOrJsonType
            awd_datetime: AwdEs\EsLibBundle\Doctrine\DBAL\Types\IDateTimeType

    orm:
        controller_resolver:
            auto_mapping: false
        auto_generate_proxy_classes: true
        mappings:
            EsLibBundle:
                is_bundle: true
                type: xml
                dir: 'src/Resources/config/doctrine'
                prefix: 'AwdEs\EsLibBundle\AwdEs'
                alias: EsLibBundle
